model: resnet50         # the model to run. see show-models for a list of available models (default=resnet18)
seed: 42           # seed to use for train-test split (default=)
accumulate: 1     # accumulate_grad_batches argument to pl.Trainer (default=1)
dropout_rate: 0.5    # the dropout rate to use (default=0.5)
optimizer: adam      # the optimizer to use (default=adam)
lr: 0.001              # the learning rate for Adam (default=0.001)
#lr_scheduler:    # the learning rate schedule to use (default=adam)
batch_size: 64     # batch size (default=64)
#hparams:         # additional hparams for the model. this should be a JSON string (default=None)
#protein:         # input contains protein sequences (default=False)
window: 4096          # the window size to use to chunk sequences (default=None)
step: 4096            # the step between windows. default is to use window size (i.e. non-overlapping chunks) (default=None)
fwd_only: False      # use forward strand of sequences only (default=False)
classify: True        # run a classification problem (default=False)
manifold: False         # run a manifold learning problem (default=False)
tgt_tax_lvl: phylum     # the taxonomic level to predict. choices are phylum, class, order, family, genus, species (default=species)
